export const orderStatusArray = [
  { label: '待确认', value: '1' },
  { label: '备货中', value: '2' },
  { label: '已发货', value: '3' },
  { label: '已取消', value: '4' },
  { label: '已完成', value: '5' },
  { label: '退货中-用户申请', value: '6' },
  { label: '退货中-商家同意退货', value: '7' },
  { label: '退货中-客服仲裁', value: '8' },
  { label: '已关闭-退货失败', value: '9' },
  { label: '退货中-客服同意', value: '10' },
  { label: '退货中-用户填写完物流', value: '11' },
  { label: '已关闭-商户同意', value: '12' },
  { label: '退货中-再次客服仲裁', value: '13' },
  { label: '已关闭-客服同意', value: '14' },
  { label: '取消退货申请', value: '15' },
  { label: '申请退款中', value: '16' },
  { label: '商户同意退款', value: '17' },
  { label: '订单退款仲裁中', value: '18' },
  { label: '退款仲裁支持用户', value: '19' },
  { label: '退款仲裁支持商家', value: '20' },
  { label: '订单退款成功', value: '21' },
  { label: '售后退款成功', value: '22' },
  { label: '退货中-再次用户申请', value: '23' },
  { label: '已关闭-退货成功', value: '24' },
  { label: '备货中-用户取消', value: '25' },
  { label: '备货中-退款商家拒绝', value: '26' },
  { label: '退货中-商家拒绝退货', value: '27' },
  { label: '退货失败', value: '28' },
  { label: '退货中-商家再次拒绝', value: '29' },
  { label: '退款中-退款申请', value: '30' },
  { label: '退款申请取消', value: '31' },
  { label: '退款成功-商家同意', value: '32' },
  { label: '退款中-商家拒绝', value: '33' },
  { label: '退款中-客服仲裁', value: '34' },
  { label: '退款中-客服同意', value: '35' },
  { label: '退款中-退款失败', value: '36' },
  { label: '已关闭-退款失败', value: '37' },
  { label: '退款中-线下退款成功', value: '38' },
  { label: '退款中-退款成功', value: '39' }
]

export const applyStatusArray = [
  { label: '退货中-用户申请', value: '6' },
  { label: '退货中-商家同意退货', value: '7' },
  { label: '退货中-客服仲裁', value: '8' },
  { label: '已关闭-退货失败', value: '9' },
  { label: '退货中-客服同意', value: '10' },
  { label: '退货中-用户填写完物流', value: '11' },
  { label: '已关闭-商户同意', value: '12' },
  { label: '取消退货申请', value: '15' },
  { label: '退货中-商家拒绝退货', value: '27' },
  { label: '退货失败', value: '28' },
  { label: '已关闭-退款失败', value: '37' }
]

export const merchantArray = [
  { label: '神创未来', value: '1' },
  { label: '佰福莱家居', value: '2' },
  { label: '深圳泽泽好物', value: '3' },
  { label: '武汉翠泽商行', value: '4' },
  { label: '小优起飞', value: '5' },
  { label: '武汉娟娟好物', value: '6' },
  { label: '武汉清华好物', value: '7' },
  { label: '勇哥商行', value: '8' },
  { label: '伟平商行', value: '9' }
]
